var arrLang = {
    'de': {
        'pHomeText': "AUSSERGEWÖHNLICHE ORTE, UNVERGLEICHLICHER LEBENSSTIL.",
        'pHomeText1': "FÜR DIEJENIGEN, DIE EIN AUSSERGEWÖHNLICHES ZUHAUSE SUCHEN.",
        'pHomeText2': "FINDEN SIE EIN ZUHAUSE, DAS ZU IHNEN PASST.",
        'h1HomeTitle': "HOME",
        'h1ImmoTitle1': 'IMMO',
        'h1ImmoTitle2': 'BILIEN',
        'h1AboutTitle1': 'ÜBER',
        'h1AboutTitle2': 'UNS',
        'h1ContactTitle1': 'KON',
        'h1ContactTitle2': 'TAKT',
        'pImmoText1': 'IN IHREM AUFTRAG NEHMEN WIR ALLE ANFRAGEN VON INTER­ES­SENTEN ENTGEGEN UND PRÜFEN, WELCHE IHREN ANFOR­DE­RUNGEN ENTSPRE­CHEN.',
        'pImmoText2': 'WIR STELLEN UNS AN IHRE SEITE, UM MIT IHNEN, IN UNSERER VERANTWORTUNG, ALLE FRAGEN RUND UM IHRE IMMOBILIE ANZUGEHEN UND TERMINGETREU DIE RICHTIGEN ANTWORTEN ZU FINDEN – VON DER SCHÄTZUNG BIS ZUM VERKAUF.',
        'pImmoText3': 'DIES UNTERANDEREM DANK EINES NETZWERKES VON QUALIFIZIERTEN BAUHERREN, ARCHITEKTEN, INVESTOREN, NOTAREN, RECHTSANWÄLTEN, FINANZINSTITUTIONEN UND WEITEREN FACHLEUTEN.',
        'pAboutUsText1': 'FÜR SIE DA - WANN IMMER SIE MÖCHTEN.',
        'pAboutUsText2': 'DAMIT WIR HÖCHSTE ANSPRÜCHE ERFÜLLEN KÖNNEN, DÜRFEN SIE JEDERZEIT MIT UNS RECHNEN. PERSÖNLICHE BETREUUNG LIEGT UNS AM HERZEN. DARUM HABEN SIE BEI SWISSPRIMEESTATE AUCH STETS DENSELBEN ANSPRECHPARTNER, DER SICH PERSÖNLICH FÜR SIE ENGAGIERT.',
        
    },
    'en': {
        'pHomeText': "EXTRAORDINARY PLACES, INCOMPARABLE LIFESTYLE.",
        'pHomeText1': "FOR THOSE LOOKING FOR AN EXCEPTIONAL HOME.",
        'pHomeText2': "FIND A HOME THAT SUITS YOUR LIFESTYLE.",
        'h1HomeTitle': "HOME",
        'h1ImmoTitle1': "REAL",
        'h1ImmoTitle2': "ESTATE",
        'h1AboutTitle1': 'ABOUT',
        'h1AboutTitle2': 'US',
        'h1ContactTitle1': 'CON',
        'h1ContactTitle2': 'TACT',
        'pImmoText1': 'ON YOUR BEHALF WE ACCEPT ALL INQUIRIES FROM INTERESTED PARTIES, AND CHECK WHICH MEET YOUR REQUIREMENTS.',
        'pImmoText2': 'WE STAND BY YOUR SIDE TO WORK WITH YOU, BUT IN OUR RESPONSIBILITY, TO ANSWER ALL YOUR QUESTIONS ABOUT YOUR PROPERTY AND TO FIND THE RIGHT ANSWERS IN TIME - FROM ESTIMATION TO SALE',
        'pImmoText3': 'THIS IS THANKS, AMONG OTHER THINGS, TO A NETWORK OF QUALIFIED LANDLORDS, ARCHITECTS, INVESTORS, NOTARIES, LAWYERS, FINANCIAL INSTITUTIONS AND OTHER EXPERTS.',
        'pAboutUsText1': 'THERE FOR YOU - WHENEVER YOU WANT.',
        'pAboutUsText2': "SO THAT WE CAN MEET THE HIGHEST DEMANDS AND YOU DO NOT LACK ANYTHING, YOU CAN COUNT ON US AT ANY TIME. PERSONAL SUPPORT IS VERY IMPORTANT TO US. THAT'S WHY YOU ALWAYS HAVE THE SAME CONTACT PERSON AT SWISSPRIMEESTATE WHO IS PERSONALLY COMMITTED TO YOU.",
    }
};

$(function(){
    $('.translate').click(function(){
        var lang = $(this).attr('id');

        $('.lang').each(function(index, element){
            $(this).text(arrLang[lang][$(this).attr('key')]);
        })
    });
});